services:
  nginx:
    image: "nginx"
    volumes:
      - "/etc/dockerized/mirrors/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/srv/mirrors:/usr/share/nginx/html"
    networks:
      - "traefik_public"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mirrors.rule=Host(`mirrors.jtremesay.org`) || Host(`mirrors.slaanesh.org`)"
        - "traefik.http.services.mirrors.loadbalancer.server.port=80"
        - "traefik.http.routers.mirrors.tls.certresolver=leresolver"

networks:
  traefik_public:
    external: true