services:
  nginx:
    image: "nginx"
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - "/srv/games:/usr/share/nginx/html"
    networks:
      - "traefik_public"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.games.rule=Host(`games.jtremesay.org`) || Host(`games.slaanesh.org`)"
        - "traefik.http.routers.games.tls.certresolver=leresolver"
        - "traefik.http.services.games.loadbalancer.server.port=80"

configs:
  nginx_config:
    file: "./nginx.conf"

networks:
  traefik_public:
    external: true