services:
  openwebui:
    image: "ghcr.io/open-webui/open-webui"
    volumes:
      - "openwebui_data:/app/backend/data"
    networks:
      - "traefik_public"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.openwebui.rule=Host(`gpt.jtremesay.org`) || Host(`gpt.slaanesh.org`)"
        - "traefik.http.routers.openwebui.tls.certresolver=leresolver"
        - "traefik.http.services.openwebui.loadbalancer.server.port=8080"

volumes:
  openwebui_data:
 
networks:
  traefik_public:
    external: true