services:
  postgres17:
    image: postgres:17
    volumes:
      - "pg17_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=nextcloud"
      - "POSTGRES_USER=nextcloud"
      - "POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_postgres_password"
    networks:
      - "default"
    secrets:
      - "nextcloud_postgres_password"

  redis:
    image: "valkey/valkey:alpine"
    command:
      - "redis-server"
      - "--save"
      - "60"
      - "1"
    volumes:
      - "redis:/data"
    networks:
      - "default"

  app:
    image: "nextcloud:31.0"
    volumes:
      - "nextcloud:/var/www/html"
    networks:
      - "default"
      - "traefik_public"
    environment:
      - "PHP_MEMORY_LIMIT=1024M"
      - "PHP_UPLOAD_LIMIT=1024M"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
        - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
        - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
        - "traefik.http.routers.nextcloud.middlewares=nextcloud-caldav@swarm"
        - "traefik.http.routers.nextcloud.rule=Host(`cloud.jtremesay.org`) || Host(`cloud.slaanesh.org`)"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
        - "traefik.http.routers.nextcloud.tls.certresolver=leresolver"

  cron:
    image: "nextcloud:31.0"
    entrypoint: "/cron.sh"
    environment:
      - "PHP_MEMORY_LIMIT=1024M"
      - "PHP_UPLOAD_LIMIT=1024M"
    volumes:
      - "nextcloud:/var/www/html"
    networks:
      - "default"

networks:
  default:
  traefik_public:
    external: true

volumes:
  pg17_data:
  redis:
  nextcloud:

secrets:
  nextcloud_postgres_password:
    external: true