borgmatic: ENC[AES256_GCM,data:6VbSS0/iUeCo5XIZhrE=,iv:fAzqd7T++WR+G1QYNpfD7iAsxr2hWChqBi6hDn5CNjk=,tag:TC0MMGDM2u4EGCDWy73dhg==,type:str]
freshrss: ENC[AES256_GCM,data:tsm+SNZseNnkbU0m,iv:0ErN3RjavS9Tk4DhuOScu7Q2xQmtIFlsomcY/MP1A3c=,tag:JNqfra0lRV++Fr9I9kTpMA==,type:str]
matrix:
    registration_shared_secret: ENC[AES256_GCM,data:x0RVLucqEajAJPTYPRs=,iv:Bgr2ISXi7Xbs/dXJcu+TULYbl6fBtK78dfSkZGygrfA=,tag:eDB9/B4fjGexBwBjQgYs3g==,type:str]
nextcloud: ENC[AES256_GCM,data:ut4uDeMko05E0rQIhAc=,iv:N41xEhEWH1fCyt1y5aHqzyxBKGEoYiSJuNXFdZWUEPE=,tag:8fNLbaeCcrN9RTueK1BXGA==,type:str]
wifi: ENC[AES256_GCM,data:+nb1crT7iU35iB77hu1qqUCFJn56k9hi3t/B4ipZ,iv:ohg8EFpknbnFZtLYqP5L+rQxT8YSHtX3oqMzqDK8LNA=,tag:LuPMmM6firUqyDye3Ep5wg==,type:str]
actalis_eab: ENC[AES256_GCM,data:alBvpDsfgDrTLDmlnCCD9lOj1HPwjJ6CDWrcTQQZGGr2V+10LvqJfmejeVHOMdRL6iZ6V2CHgIdgm3+KUWJ9G8v9wlQyWQ9pMtQOmUuxe76GWWL+QA9dT2hh3NJMFA==,iv:JPpSmUKXivdh0Ty3E3xsoJgte6u6V+QwcqpNmzW9ChI=,tag:WtfbD0yBbTZiTmlctv39fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQlB3bmNlRGw3M01XZUww
            WUQ3alhpZEllL1ZvcitFTUZWNDlzbmdNUEdNCkNmMkFnblhTWllCYUlxVksvdnRT
            ZjN6QWdXY0YzT3BISVZlZFVsVS9oVVUKLS0tIEQzQXNNOC9oNFU1NFp5MlNjeWF5
            NG5DbjhpRmNmbzJhWStBYWYvUG40akEKbZqu4QEm7cvt+OXmkAVP5tkaBUEt4dGv
            ouXTQqbCU76dZUK7hETarkzqV8qK77dZjxc/TjzxSeYswDrelUJIsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ma7y9pzj5dk04j3jvjde3esfm6led6duludqk375k7hz93jc5a2scmw3ve
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTHpxMGh3Q0k3R3BaOWFt
            bEhVS1crT2hQUXlHSXlkaW1kdUNlc0MvZG1NCkcvaTN2Y0pUNnd5eVNUQ1RTM0Nt
            bFZoZEZZUXEyeVVkSU5MZXFwUW9TZ3MKLS0tIEMvWHorY1FPeG1wQmRZZXhzU096
            RkVsVll2RWZlS0hPQUNHOTl0R3QvQ0kKjfSRsi/ZAierehubVUVIr8lwsQoP369k
            aIGPrM5MluLTQndrkJSHl4QN9Quna6XK+Ir8xkp72egJNbBm6BP/jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15qk2hwshn3wrqez9t7wgunyucu9fgdn3lpdr6k83ah2a5tvt793sg2sdn2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Rkd2Vk5XYUdTNHVJU3BY
            L3dmRWdkeUo1dlNZLzE4eUVMU3U0YUJHQ244Ci94SkpBZjlwMGM1TUVVUDc3Qndw
            SmxLeTJvaXVVaHRMQjVSOXUrU2ViZmcKLS0tIG1vc2FjME8wbmtsZ2FlY0xnZGpK
            SDc4ejJlVlIvcVRSOVZPWnVFWHh4NlUKpC3032ily7iCdwNTgQCeZDWIV5uwzozr
            uO39Yxhc6PFy7hexFh2dHB+9bRRfRKUKuWKnfIjNrTxUhUW/Ky8PvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2q78sfsycx533vq5umcntpe3049c0gp92d38a4307zndylppv4qfdqshc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q1FjTXExeUh1SlUvSzdB
            elpZQlNwM3VuM0tGUjVKWGVFVXVvZXY3Mng0CjZrYUI0UFRVU1ZnSFBGN2pqZEJC
            MFBra242MllDQ0FRRVFsWHYxdmJxWHcKLS0tIFVEaGlLSy95Sm8zZWp2Qll4ckNr
            UFFoUkhyWjBsNlNSSEhRNXl1dmhhUUkKuFIA6TlNC4dPrZBcmEOJ9rY6KOeMiNz8
            j3406YUggeHdV6uXXdj4VPugQ7jCsvUfv+0ZCYXCArrivJAUf7V60g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ngm6g0yel2yrzfqauwq6jzz9ha0rxecwuvud7tt38qv8lzcptvxsmslkgh
    lastmodified: "2026-06-10T19:49:07Z"
    mac: ENC[AES256_GCM,data:JeK0X7K2H6rLAvrinKQf5ARcBBE9m8sdViK2yRopPk0Emkf6hrhH0ByU5UazUJzYH0SYw46d/0XOzeIQiulg+Hbs8Mam83GClfcP0Ec8acZucRTCFNMU13fIA2hdupFb31CK6Lu0umTMlxFgzZY/ATExEyOn6SZE+DpFSbkaf2s=,iv:/5DQ+e0kqv8/Beg5K1JiyFOGmd9fvavTC2PAZJ3xhc4=,tag:jV/MCwBi/TEax3V96Eao1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
